Bump grpc version from 1.48.0 to 1.49.0
This is to address a build error caused by a bug in grpc 1.48.0:
‘absl::lts_20220623::StatusOr<grpc_core::Json> grpc_core::{anonymous}::ParseHttpFaultIntoJson(upb_StringView, upb_Arena*)’: ./repo-third-party-build/grpc-repo/src/grpc/src/core/ext/xds/xds_http_fault_filter.cc:112:39: error: expected ‘)’ before ‘and’
if (abort_http_status_code != 0 and abort_http_status_code != 200) {